maintainer        "resque"
maintainer_email  "sysadmins@37signals.com"
description       "Configures Resque"
version           "0.1"
depends           "nginx"
depends           "thin"
depends           "bluepill"