maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures nagios"
version           "0.1"
depends           "runit"
depends           "fcgiwrap"
depends           "nginx"
depends           "ssl_certificates"
depends           "users"