#!/usr/local/bin/ruby

require 'fileutils'

date = Time.now.strftime("%m-%d-%Y")
apps = ARGV[0].split(",")

apps.each do |app|
  email_dir = "/u/apps/#{app}/shared/email"
  rotate_dir = File.join(email_dir, "/old/#{date}")

  FileUtils.mkdir_p(rotate_dir)

  %W(completed failed junk).each do |dir|
    src = File.join(email_dir, dir)
    next unless File.exist?(src)
    dest = File.join(rotate_dir, dir)

    FileUtils.mv(src, dest)

    %W(cur new tmp).each do |folder|
      FileUtils.mkdir_p(File.join(email_dir, dir, folder))
    end
  end
end
