integrity Mash.new unless attribute?(:integrity)
integrity[:server_name] = "integrity.37signals.com" unless integrity.has_key?(:server_name)
integrity[:url] = "http://#{integrity[:server_name]}" unless integrity.has_key?(:url)
integrity[:path] = "/u/apps/integrity" unless integrity.has_key?(:path)
integrity[:db_uri] = "sqlite3://#{integrity[:path]}/integrity.db" unless integrity.has_key?(:db_uri)
integrity[:export_dir] = "#{integrity[:path]}/builds" unless integrity.has_key?(:export_dir)
integrity[:log_file] = "#{integrity[:path]}/log/integrity.log" unless integrity.has_key?(:log_file)
integrity[:basic_auth] = "true" unless integrity.has_key?(:basic_auth)
integrity[:admin_username] = "admin" unless integrity.has_key?(:admin_username)
integrity[:admin_password] = "12345678" unless integrity.has_key?(:admin_password)
integrity[:hash_admin_password] = "true" unless integrity.has_key?(:hash_admin_password)
