maintainer        "37signals"
maintainer_email  "sysadmins@37signals.com"
description       "Configures rails"
version           "0.1"
depends           "unicorn"
depends           "thin"
depends           "runit"
depends           "logrotate"
depends           "bluepill"
depends           "ssl_certificates"
depends           "aws"
depends           "bundler"
depends           "mysql"